---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 10.7.6
  - name: community.crypto
    version: 2.26.6
  - name: community.docker
    version: 4.8.4 
